### ISSUE TITLE
Feature Request: Support for S3 chart storage

### ISSUE THREAD

**Issue by josdotso** [flaper87/pyhelm#10]
https://github.com/hypnoglow/helm-s3

I'm interested in using pyhelm via Ansible's helm module, but I am blocked because I need to store my charts in S3.  Is the helm-s3 behavior something pyhelm could support?

**Comment by flaper87** [comment]
@josdotso Hey, I'm ok with this. Unfortunately, I've close to no time to work on `pyhelm` now. If you are down to help out, I'm more than happy to help reviewing and even add you to the collaborators, if you want. :)

**Comment by ljakimczuk** [comment]
@flaper87 if there are no other volunteers, I'm more than happy to try to add it with boto3 :)

**Comment by yanivoliver** [comment]
@ljakimczuk - Go ahead :)

**Comment by yanivoliver** [comment]
Resolved by https://github.com/flaper87/pyhelm/pull/26
