### ISSUE TITLE
Please provide examples on how to determine Tiller host in README

### ISSUE THREAD

**Issue by zerogjoe** [flaper87/pyhelm#18]
I am trying to follow your StackOverflow answer here:

https://stackoverflow.com/questions/49311795/code-sample-to-deploy-a-helm-chart-via-api

1.  Can this example be added to the README.md for people who find this repo first?
2.  What is missing from the example is instantiating the `Tiller` class. To instantiate a `Tiller` you need to provide the `host` parameter. However, it's not at all clear how you determine what this should be from an existing command-line helm installation. Help!

**Comment by zerogjoe** [comment]
Related question: is it possible to use helm's tunneling connection to tiller, or can this library only be used from within the cluster?

**Comment by yanivoliver** [comment]
@zerogjoe - Tiller does not expose it's service endpoint outside of the cluster (it's ClusterIP). An approach to overcome this is build a port-forwarding tunnel using kubectl. For example,
```
kubectl port-forward <TILLER_POD_NAME> 44134 -n kube-system
```
While the process is up (the tunnel lives as long as the the command is still running), you can set the Tiller host to be localhost, listening in port 44134.
