### ISSUE TITLE
Receive message max size & RELEASE_LIMIT

### ISSUE THREAD

**Issue by ljakimczuk** [flaper87/pyhelm#24]
Hi! I'd like to ask for the expertise :)

I've encountered the "Received message larger than max" problem:

`grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Received message larger than max (6147341 vs. 4194304))`

This is the result from the environment with hundreds of releases and with some of them having more than 200 revisions, so I guess I kind of brought this on myself, but wouldn't it make sense to add `options` to the `insecure_channel` and leave the max size opened for configuration, e.g., like the RELEASE_LIMIT? Speaking of which, I hit the problem when trying to increase this limit. It's current value is too small for me and I didn't spotted any other way of getting the complete list of deployed stuff than to tweak it. And this is how I got to the the max size changing idea and although it works, it does not seem really transparent nor long-term approach. I guess, except really high values, it would be just postponing the inevitable. Does it make sense? 

Eventually, I thought of using the `offset` in the request and even decreasing the current release limit, so in result of getting the complete list of releases, but in smaller chunks. Does not need to know the current and most importantly the possible maximum message's size and returns the whole list at the end.

Here is what I've changed in order to push my use-case through:

```diff
--- a/pyhelm/tiller.py
+++ b/pyhelm/tiller.py
@@ -12,6 +12,7 @@ TILLER_PORT = 44134
 TILLER_VERSION = b'2.9.1'
 TILLER_TIMEOUT = 300
 RELEASE_LIMIT = 64
+RECEIVED_MSG_MAX = 4194304
 
 
 class Tiller(object):
@@ -43,7 +44,10 @@ class Tiller(object):
         '''
         Return a tiller channel
         '''
-        return grpc.insecure_channel('%s:%s' % (self._host, self._port))
+        return grpc.insecure_channel('%s:%s' % (self._host, self._port),
+                                    options=[
+                                        ('grpc.max_receive_message_length', RECEIVED_MSG_MAX),
+                                    ])
 
     def tiller_status(self):
         '''
@@ -59,12 +63,20 @@ class Tiller(object):
         List Helm Releases
         '''
         releases = []
+
+        offset = None
         stub = ReleaseServiceStub(self.channel)
-        req = ListReleasesRequest(limit=RELEASE_LIMIT)
-        release_list = stub.ListReleases(req, self.timeout,
-                                         metadata=self.metadata)
-        for y in release_list:
-            releases.extend(y.releases)
+
+        while (offset is None or len(offset) > 0):
+
+            req = ListReleasesRequest(limit=RELEASE_LIMIT,offset=offset)
+            release_list = stub.ListReleases(req, self.timeout,
+                                            metadata=self.metadata)
+        
+            for y in release_list:
+                offset = str(y.next)
+                releases.extend(y.releases)
+        
         return releases
```

**Comment by yanivoliver** [comment]
What you say makes perfect sense - I don't see much use of adding the _RECEIVED_MSG_MAX_ option, as it does not solve the problem in all cases, but adding pagination to the release listing is a good solution.

Go ahead and open a PR so we can work on merging this in.

Thanks!

**Comment by ljakimczuk** [comment]
Thanks! Glad it makes sense, I've opened the PR :)

**Comment by yanivoliver** [comment]
Resolved by https://github.com/flaper87/pyhelm/pull/25
