### ISSUE TITLE
unable to install pyhelm - error in pygit

### ISSUE THREAD

**Issue by Formartha** [flaper87/pyhelm#27]
Hi,

trying to install pyhelm produces the following issue:

[root@QA-Machine orion]# pipenv install pyhelm
Installing pyhelm?
Looking in indexes: http://aeenexus3:8081/repository/PyPi-All/simple
Collecting pyhelm
  Downloading http://aeenexus3:8081/repository/PyPi-All/packages/c1/53/bd8bf05de4cfdf4b7654b1651e697657e0a14fa428bb872f59d5f20aebef/pyhelm-0.0.1.dev39-py2-none-any.whl
Collecting grpcio-tools==1.1.3 (from pyhelm)
  Downloading http://aeenexus3:8081/repository/PyPi-All/packages/43/3c/3778dd957253e7f4ff7da02efd9bdf1bfd5f809170245430b8613cc377c3/grpcio_tools-1.1.3-cp27-cp27m-manylinux1_x86_64.whl (19.3MB)
Collecting pygit2>=0.24.2 (from pyhelm)
  Downloading http://aeenexus3:8081/repository/PyPi-All/packages/fe/48/f85a605b7337b5562dff902ba1a50d8f22d399e0b623d0c48363dc84fa81/pygit2-0.27.1.tar.gz (477kB)
Collecting protobuf==3.2.0 (from pyhelm)
  Downloading http://aeenexus3:8081/repository/PyPi-All/packages/43/16/cdfe80080683b5a76ea489a516bb5859f1550476fdec9b20260987fa42c6/protobuf-3.2.0-py2.py3-none-any.whl (360kB)
Collecting requests==2.14.2 (from pyhelm)
  Downloading http://aeenexus3:8081/repository/PyPi-All/packages/e4/b0/286e8a936158e5cc5791d5fa3bc4b1d5a7e1ff4e5b3f3766b63d8e97708a/requests-2.14.2-py2.py3-none-any.whl (560kB)
Collecting supermutes==0.2.5 (from pyhelm)
Collecting PyYAML==3.12 (from pyhelm)
  Downloading http://aeenexus3:8081/repository/PyPi-All/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.12.tar.gz (253kB)
Collecting grpcio==1.1.3 (from pyhelm)
  Downloading http://aeenexus3:8081/repository/PyPi-All/packages/ab/ca/ce0784be137d4ac2ca3ba6a8760190d007487f13fd70b1b0a0cab54e39d5/grpcio-1.1.3-cp27-cp27m-manylinux1_x86_64.whl (5.0MB)
Requirement already satisfied: cffi in ./.venv/lib/python2.7/site-packages (from pygit2>=0.24.2->pyhelm) (1.11.5)
Requirement already satisfied: six in ./.venv/lib/python2.7/site-packages (from pygit2>=0.24.2->pyhelm) (1.11.0)
Requirement already satisfied: setuptools in ./.venv/lib/python2.7/site-packages (from protobuf==3.2.0->pyhelm) (40.0.0)
Collecting futures>=2.2.0 (from grpcio==1.1.3->pyhelm)
  Downloading http://aeenexus3:8081/repository/PyPi-All/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Requirement already satisfied: enum34>=1.0.4 in ./.venv/lib/python2.7/site-packages (from grpcio==1.1.3->pyhelm) (1.1.6)
Requirement already satisfied: pycparser in ./.venv/lib/python2.7/site-packages (from cffi->pygit2>=0.24.2->pyhelm) (2.18)
Building wheels for collected packages: pygit2, PyYAML
  Running setup.py bdist_wheel for pygit2: started
  Running setup.py bdist_wheel for pygit2: finished with status 'error'
  Running setup.py clean for pygit2
  Running setup.py bdist_wheel for PyYAML: started
  Running setup.py bdist_wheel for PyYAML: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/77/46/55/9c2501fdc1914400fbda88b72293ca0822364f9f1a9e313c38
Successfully built PyYAML
Failed to build pygit2
Installing collected packages: futures, protobuf, grpcio, grpcio-tools, pygit2, requests, supermutes, PyYAML, pyhelm
  Running setup.py install for pygit2: started
    Running setup.py install for pygit2: finished with status 'error'

Error:  An error occurred while installing pyhelm!
  Failed building wheel for pygit2
Command "/root/PycharmProjects/orion/.venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-84J42Y/pygit2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-zzCLTo/install-record.txt --single-version-externally-managed --compile --install-headers /root/PycharmProjects/orion/.venv/include/site/python2.7/pygit2" failed with error code 1 in /tmp/pip-install-84J42Y/pygit2/

[root@QA-Machine orion]# pipenv install pyhelm

Installing pyhelm?
Looking in indexes: http://aeenexus3:8081/repository/PyPi-All/simple
Collecting pyhelm
  Downloading http://aeenexus3:8081/repository/PyPi-All/packages/c1/53/bd8bf05de4cfdf4b7654b1651e697657e0a14fa428bb872f59d5f20aebef/pyhelm-0.0.1.dev39-py2-none-any.whl
Requirement already satisfied: grpcio-tools==1.1.3 in ./.venv/lib/python2.7/site-packages (from pyhelm) (1.1.3)
Collecting pygit2>=0.24.2 (from pyhelm)
  Downloading http://aeenexus3:8081/repository/PyPi-All/packages/fe/48/f85a605b7337b5562dff902ba1a50d8f22d399e0b623d0c48363dc84fa81/pygit2-0.27.1.tar.gz (477kB)
Requirement already satisfied: protobuf==3.2.0 in ./.venv/lib/python2.7/site-packages (from pyhelm) (3.2.0)
Collecting requests==2.14.2 (from pyhelm)
  Downloading http://aeenexus3:8081/repository/PyPi-All/packages/e4/b0/286e8a936158e5cc5791d5fa3bc4b1d5a7e1ff4e5b3f3766b63d8e97708a/requests-2.14.2-py2.py3-none-any.whl (560kB)
Collecting supermutes==0.2.5 (from pyhelm)
Collecting PyYAML==3.12 (from pyhelm)
Requirement already satisfied: grpcio==1.1.3 in ./.venv/lib/python2.7/site-packages (from pyhelm) (1.1.3)
Requirement already satisfied: cffi in ./.venv/lib/python2.7/site-packages (from pygit2>=0.24.2->pyhelm) (1.11.5)
Requirement already satisfied: six in ./.venv/lib/python2.7/site-packages (from pygit2>=0.24.2->pyhelm) (1.11.0)
Requirement already satisfied: setuptools in ./.venv/lib/python2.7/site-packages (from protobuf==3.2.0->pyhelm) (40.0.0)
Requirement already satisfied: futures>=2.2.0 in ./.venv/lib/python2.7/site-packages (from grpcio==1.1.3->pyhelm) (3.2.0)
Requirement already satisfied: enum34>=1.0.4 in ./.venv/lib/python2.7/site-packages (from grpcio==1.1.3->pyhelm) (1.1.6)
Requirement already satisfied: pycparser in ./.venv/lib/python2.7/site-packages (from cffi->pygit2>=0.24.2->pyhelm) (2.18)
Building wheels for collected packages: pygit2
  Running setup.py bdist_wheel for pygit2: started
  Running setup.py bdist_wheel for pygit2: finished with status 'error'
  Running setup.py clean for pygit2
Failed to build pygit2
Installing collected packages: pygit2, requests, supermutes, PyYAML, pyhelm
  Running setup.py install for pygit2: started
    Running setup.py install for pygit2: finished with status 'error'

Error:  An error occurred while installing pyhelm!
  Failed building wheel for pygit2
Command "/root/PycharmProjects/orion/.venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-DB_5PQ/pygit2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-wmTDT9/install-record.txt --single-version-externally-managed --compile --install-headers /root/PycharmProjects/orion/.venv/include/site/python2.7/pygit2" failed with error code 1 in /tmp/pip-install-DB_5PQ/pygit2/

**Comment by yanivoliver** [comment]
What version of pyhelm are you trying to install? From your logs, it seems your trying to install it from a private pypi instance.
The latest pyhelm version doesn't depend on pygit2.

**Comment by yanivoliver** [comment]
The version on pypi (0.0.2) is from November 13th, which as I verified, does not depend on pygit2.
The commits merged in afterwards are not part of a released version, yet. Are you missing any of them specifically?

**Comment by yanivoliver** [comment]
Anyhow, I've uploaded version 0.0.3 to pypi. You're welcome to give it a try.

**Comment by Formartha** [comment]
the issue is related to the way you are building your requirements.
bumping the versions will aid with it.
for example, pyyaml uses it pygit

**Comment by yanivoliver** [comment]
pyyaml does not use pygit2. You're being vague - what are you suggesting here?
The output snippet you've attached here is obviously not up to date. Do you have a relevant output of an up-to-date version of pyhelm you're having trouble with?

**Comment by yanivoliver** [comment]
@Formartha - Closing the issue due to inactivity. Please reopen if you still encounter this problem.
