### ISSUE TITLE
Is there a way to connect to Tiller using TLS?

### ISSUE THREAD

**Issue by juanmagal** [flaper87/pyhelm#48]
I am thinking on securing my Helm installation by using TLS towards my Tiller deployment (--tls option). As far as I see the only options I can use to connect to Tiller using pyhelm are "host" and "port", is there a way to provide the TLS certificates to be used?

Thanks!

**Comment by yanivoliver** [comment]
Sorry for the late response. Support for TLS has been added. See #56 for details, but in general you can pass a TLS class instance when instantiating a Tiller instance.
