### ISSUE TITLE
Provide support for listing all helm releases

### ISSUE THREAD

**Issue by michalvanco** [flaper87/pyhelm#50]
This piece of code:
```
    def list_releases(self):
        """
        List Helm Releases
        """
        releases = []

        offset = None
        stub = ReleaseServiceStub(self._channel)

        while True:
            req = ListReleasesRequest(limit=RELEASE_LIMIT, offset=offset)
            release_list = stub.ListReleases(req, self._timeout,
                                             metadata=self.metadata)
```
currently lists only the helm releases in `DEPLOYED` state.

See related code - https://github.com/helm/helm/blob/master/pkg/tiller/release_list.go#L31, https://github.com/helm/helm/blob/master/_proto/hapi/release/status.proto.

Would it be possible to make a support for listing `ALL` or selected statuses in `pyhelm` client?

Thank you in advance.

Context:
* we are using the `pyhelm` inside our garbage-collector tool running as k8s cronjob and we need to garbage all helm releases which are not needed anymore (incl. failed and other statuses)

**Comment by yanivoliver** [comment]
Makes sense, and looks simple enough to implement. I'll try to get to this.

**Comment by michalvanco** [comment]
Thanks @yanivoliver!!!

**Comment by yanivoliver** [comment]
@michalvanco - You're welcome :) Let me know if you encounter any issues.

**Comment by michalvanco** [comment]
Hi @yanivoliver,
sorry I totally forget to reach you back :( I just wanted to share that the listing of helm releases with various statuses works as expected and we have immediately upgraded our tool to the new version (long time ago).

Thank you once more and good luck with maintaining the project!

**Comment by yanivoliver** [comment]
@michalvanco No worries, glad to hear :)
