### ISSUE TITLE
Post-install hooks runs almost along with the charts

### ISSUE THREAD

**Issue by vijay-v6** [flaper87/pyhelm#51]
With pyhelm Post-install hooks runs almost along with the charts and its dependent charts. But actual helm waits for atleast one container to be running for a pod before proceeding to post-install hook. How do we get around this?

**Comment by yanivoliver** [comment]
By default, Helm does not wait for pods to be in running state before executing post-install hooks. The behaviour you're describing happens when you use the "wait" option, which pyhelm supports as well. Have you tried it?
