### ISSUE TITLE
Question about two semi-duplicated pyhelm repo

### ISSUE THREAD

**Issue by adolli** [flaper87/pyhelm#54]
I saw another pyhelm implementation at this repo https://github.com/daewood/pyhelm/tree/master/build/lib, there are nearly the same code I've compared. Would u tell me what is the relation ship between these two repo?

**Comment by yanivoliver** [comment]
The repo you're referring to is a fork of this. This is the main pyhelm repo.

**Comment by adolli** [comment]
Thank u. I think so. The fork of this seems not professional at all as it contains many .pyc files.

**Comment by adolli** [comment]
Oh, by the way, this project really helps a lot to me!
