### ISSUE TITLE
Character encoding error when trying to deploy stable/metallb

### ISSUE THREAD

**Issue by miff2000** [flaper87/pyhelm#65]
When I try to deploy [stable/metallb](https://github.com/helm/charts/tree/master/stable/metallb) using Ansible, I get a weird error back about character encoding. I am not passing in any values at all, so this is using the chart's defaults.

The error I see is this:
<pre>
TASK [build-namespaces : Deploy MetalLB] *********************************************************************************************************************************************************************************************************************************************************************************************************************************fatal: [localhost -> 172.31.50.3]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 172.31.50.3 closed.\r\n", "module_stdout": "2019-05-10 13:49:24,287 - ChartBuilder - INFO - Cloning https://kubernetes-charts.storage.googleapis.com/ for release metallb\r\n2019-05-10 13:49:48,375 - ChartBuilder - INFO - File:README.md\r\nTraceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1557492564.6152759-11505359592173/AnsiballZ_helm.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1557492564.6152759-11505359592173/AnsiballZ_helm.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1557492564.6152759-11505359592173/AnsiballZ_helm.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_helm_payload_mXW8k6/__main__.py\", line 184, in <module>\r\n  File \"/tmp/ansible_helm_payload_mXW8k6/__main__.py\", line 172, in main\r\n  File \"/tmp/ansible_helm_payload_mXW8k6/__main__.py\", line 113, in install\r\n  File \"/usr/lib/python2.7/site-packages/pyhelm/chartbuilder.py\", line 224, in get_helm_chart\r\n    files=self.get_files(),\r\n  File \"/usr/lib/python2.7/site-packages/pyhelm/chartbuilder.py\", line 153, in get_files\r\n    chart_files.append(Any(type_url=filename, value=fd.read().encode()))\r\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1358: ordinal not in range(128)\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
</pre>

Made prettier, the important error seems to be:
> File \"/usr/lib/python2.7/site-packages/pyhelm/chartbuilder.py\", line 152, in get_files\r\n    chart_files.append(Any(type_url=filename, value=fd.read().encode()))\r\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1358: ordinal not in range(128)

**Comment by miff2000** [comment]
This appears to be the same error [reported here](https://stackoverflow.com/questions/18649512/unicodedecodeerror-ascii-codec-cant-decode-byte-0xe2-in-position-13-ordinal).

The suggestion there is to use Python's [codecs](http://docs.python.org/2/library/codecs.html) module. Although the link is for Python 2, it does also exist in Python 3 by the looks of it.

**Comment by miff2000** [comment]
I'll put together a PR to use the codecs module when opening files, as this should avoid any character set issues moving forward. It should be trivial so I'll do this today hopefully

**Comment by yanivoliver** [comment]
Resolved by #72
