### ISSUE TITLE
Deployment Metadata

### ISSUE THREAD

**Issue by stevencox** [flaper87/pyhelm#76]
Is there a way to get metadata about a deployed chart?

If I use PyHelm to deploy a chart containing a pod and service - can I get the port the service is listening on (and other data about the pod, etc)? This would allow writing a client that can immediately make use of a deployment.

@muralikarthikk

**Comment by yanivoliver** [comment]
You can get the metadata of installed releases using the Tiller class. Take note it contains little data about the state of the installed resources, as Helm doesn't track the state of services.
You could always just the Kubernetes API and query whatever installed resources you want.

**Comment by stevencox** [comment]
Sounds good. Thanks.
