### ISSUE TITLE
URL concatination in repo._get_from_http() fails on Windows machines.

### ISSUE THREAD

**Issue by reidarkind** [flaper87/pyhelm#77]
Line 55 in repo.py is:
`file_url = os.path.join(repo_url, file_url)`

When using a Windows machine the URL will then be: 'https://some-url.com**\**index.yaml'

By changing to:
`file_url = '{0}/{1}'.format(repo_url, file_url)`
it will work also on Windows machines.

**Comment by yanivoliver** [comment]
Thanks. Feel free to create a PR and we'll work on getting this in

**Comment by yanivoliver** [comment]
This issue has been resolved. Feel free to reopen if it persists.
