### ISSUE TITLE
install failed on mac

### ISSUE THREAD

**Issue by joaocc** [flaper87/pyhelm#9]
I'm using python3 on mac OS
```
$ pip3 install pyhelm
Collecting pyhelm
  Using cached pyhelm-0.0.1.dev33.tar.gz
Collecting grpc==0.3.post19 (from pyhelm)
  Using cached grpc-0.3-19.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/x0/0fb1ckx53f58_t_yh8shttm80000gp/T/pip-build-71bgup46/grpc/setup.py", line 7, in <module>
        version_tuple = __import__('grpc').VERSION
      File "/private/var/folders/x0/0fb1ckx53f58_t_yh8shttm80000gp/T/pip-build-71bgup46/grpc/grpc/__init__.py", line 6, in <module>
        from .rpc import *
      File "/private/var/folders/x0/0fb1ckx53f58_t_yh8shttm80000gp/T/pip-build-71bgup46/grpc/grpc/rpc.py", line 141
        except OSError, ex:
                      ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/x0/0fb1ckx53f58_t_yh8shttm80000gp/T/pip-build-71bgup46/grpc/
```

Any ideas?
Thx

**Comment by flaper87** [comment]
Sounds like this may have been fixed by: https://github.com/flaper87/pyhelm/issues/7

Have you tried latest from this repo? I'll release a new version if this works for you

**Comment by joaocc** [comment]
Hi.
Thx for the update. I am not sure if I did. I went for the plain ```pip3 install pyhelm```.
If you provide me with the command you want me to test, I'll try and let you know quite quickly.
Thx

**Comment by joaocc** [comment]
A bit more research, I think I am installing pyhelm (0.0.1.dev33), which according to  https://pypi.python.org/pypi/pyhelm/0.0.1.dev33 is from 2017-05-21.
The source is pointing to https://docs.openstack.org/developer/pyhelm, which seems to be broken.
Ideally, the pip repository should be updated, so more people can benefit.
Thx

**Comment by joaocc** [comment]
It works. 
```$ pip3 install git+https://github.com/flaper87/pyhelm.git```
However, I had to install libgit2 first
```$ brew install libgit2```
It would be great if you could create a new release with the current master.
Thx

**Comment by flaper87** [comment]
Alright! I'll do it asap. 

Thanks!

**Comment by pjanuario** [comment]
@flaper87 let us know once you have published a new version I will give it a try too.. As I mentioned [here](https://github.com/ansible/ansible/issues/29661) I had some troubles installing it from the source.

**Comment by flaper87** [comment]
@pjanuario new version should be up

**Comment by pjanuario** [comment]
@flaper87 thanks. I was able to build the master and run the master. 
Unfortunately, In my case I have a lot of properties such as passwords and I prefer to use a file for configuration and the ansible module doesnt support it.

I know there is a ticket for this https://github.com/ansible/ansible/issues/31117

**Comment by joaocc** [comment]
@pjanuario I had a similar situation, and the workaround was to load the file to memory as YAML and using that as parameter to the ansible module. I know this is not perfect, but maybe it can help in a pinch.

**Comment by pjanuario** [comment]
I also considered the same. Maybe I will give it a try.

**Comment by yanivoliver** [comment]
Installation now work on OS X.
